#!/usr/bin/env bash
# https://github.com/ldelossa/sway-fzfify
window_id=$(swaymsg -t get_tree| jq -r 'recurse(.nodes[]?) | recurse(.floating_nodes[]?) | select(.type=="con"), select(.type=="floating_con") | select((.app_id != null) or .name != null) | {id, app_id, name} | [.id, .app_id]|join(":")' | fuzzel --dmenu | cut -d ":" -f1)

if [[ -z $window_id ]]; then
    exit
fi

swaymsg "[con_id=$window_id]" focus
