hostname *
shell_integration inherited

# Optional: remote sessions visually distinguishable
# color_scheme Tomorrow Night

# Optional: if a weird remote host has bootstrap trouble
# hostname *.bsd old-host
# interpreter python
