[matching]
'miyo-desktop' = '∑'
'md.obsidian.Obsidian' = '󰇈'
'firefox' = ''
'KeePass2' = ''
'org.keepassxc.KeePassXC' = ''
'betterbird' = '󰇰'
'eu.betterbird.Betterbird' = '󰇰'
'/(?i)mattermost/' = '󰭹'
'com.mattermost.Desktop' = '󰭹'
'chromium' = ''
'chromium-browser' = ''
'com.saivert.pwvucontrol' = '󰓃'
'signal' = ''
'nwg-displays' = '󰍺'
'org.kde.gwenview' = '󰋩'
'imv' = ''
'/Yazi:/' = ''
'/yay/' = ''
'/updateall/' = ''
'/rsync/' = ''
'/python/' = ''
'org.strawberrymusicplayer.strawberry' = ''
'audacious' = ''
'/nvim ?\w*/' = ''
'/htop/' = '󰄪'
'kitty' = ''
'libreoffice-writer' = ''
'libreoffice-calc' = ''
'io.github.Qalculate.qalculate-qt' = ''
'blueman-manager' = ''
'code' = '󰨞'
'gimp' = ''
'org.kde.okular' = ''
'org.gnome.Evince' = ''
'sonic-visualiser' = '󱑽'
'org.inkscape.Inkscape' = ''
'org.openscad.openscad' = '󰆧'
'openscad' = '󰆧'
'BambuStudio' = '󰹛'
'bambu-studio' = '󰹛'
'org.wireshark.Wireshark' = '󱙳'
'nm-connection-editor' = '󰌗'
'nm-applet' = '󰖩'
'remarkable.exe' = '󰓶'
'org.telegram.desktop' = ''
