[[manager.prepend_keymap]]
on  = "<C-n>"
run = 'shell -- dragon-drop -x -i -T "$@"'

[[manager.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[manager.prepend_keymap]]
on = "o"
run = "shell 'handlr open \"$@\"'"
