[[mgr.prepend_keymap]]
on  = "<C-n>"
run = 'shell -- dragon-drop -x -i -T "$@"'

[[mgr.prepend_keymap]]
on = "<A-y>"
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = "o"
run = "shell 'handlr open \"$@\"'"
