theme = "monokai"

[editor]
scrolloff = 5
shell = ["fish", "-c"]
cursorline = true
bufferline = "multiple"
soft-wrap.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
right = [
  "diagnostics",
  "version-control",
  "selections",
  "register",
  "file-type",
  "file-encoding",
  "position",
  "position-percentage",
  "file-line-ending"
]

[keys.normal]
C-A-r = ":set-option line-number relative"
C-A-a = ":set-option line-number absolute"
C-c = ":clipboard-yank-join"
"C-," = "toggle_comments"

[keys.select]
C-c = ":clipboard-yank-join"
"C-," = "toggle_comments"

[editor.indent-guides]
render = true
character = "┊"

#[editor.whitespace]
#render = "all"
# or control each character
[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)
